version: '3'
services:
  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: ccd-elasticsearch
    environment:
      - cluster.name=ccd-docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - compose_default

  ccd-logstash:
    image: ccd-logstash:latest
    container_name: ccd-logstash
    depends_on:
          - "ccd-elasticsearch"
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - compose_default

volumes:
  esdata1:
    driver: local

networks:
  compose_default:
    external: true

